### ISSUE TITLE
运行完后， localhost:8080 没有连接

### ISSUE THREAD

**Issue by 465788227** [xjk971020/QQMusic#2]

**Comment by xjk971020** [comment]
有没有按照规定启动运行所需环境？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"465788227"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月27日(星期一) 凌晨3:55
收件人:&nbsp;"xjk971020/QQMusic"<QQMusic@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[xjk971020/QQMusic] 运行完后， localhost:8080 没有连接 (#2)

**Comment by 465788227** [comment]
> 有没有按照规定启动运行所需环境？
npm i, npm run serve 都成功。

**Comment by xjk971020** [comment]
接口项目有没有启动，是8080整个无法连接还是说有界面但是没有数据？
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"465788227"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月27日(星期一) 中午1:48
收件人:&nbsp;"xjk971020/QQMusic"<QQMusic@noreply.github.com&gt;;
抄送:&nbsp;"佳"<823840954@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xjk971020/QQMusic] 运行完后， localhost:8080 没有连接 (#2)





  
有没有按照规定启动运行所需环境？
 npm i, npm run serve 都成功。

**Comment by 465788227** [comment]
> 。。。

整个，接口项目如何启动？

**Comment by xjk971020** [comment]
加我微信xjk9710




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"465788227"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月27日(星期一) 下午2:27
收件人:&nbsp;"xjk971020/QQMusic"<QQMusic@noreply.github.com&gt;;
抄送:&nbsp;"佳"<823840954@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xjk971020/QQMusic] 运行完后， localhost:8080 没有连接 (#2)





  
。。。
  
整个，接口项目如何启动？

**Comment by 465788227** [comment]
我不有微信，如果复杂，我会关闭这个问题，谢谢你！

**Comment by xjk971020** [comment]
如果是localhost:8080访问显示无法连接的话就是前端项目启动失败了，你可以进入vue ui中看看系统的启动日志，看看是不是启动前端项目的时候出现问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"465788227"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月27日(星期一) 下午2:43
收件人:&nbsp;"xjk971020/QQMusic"<QQMusic@noreply.github.com&gt;;
抄送:&nbsp;"佳"<823840954@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xjk971020/QQMusic] 运行完后， localhost:8080 没有连接 (#2)





 
我不有微信，如果复杂，我会关闭这个问题，谢谢你！

**Comment by 465788227** [comment]
在终端：
![2](https://user-images.githubusercontent.com/51926728/80344377-ae0dd900-8891-11ea-95b9-d62f7c291f9a.png)
在VueUi:
![2020-04-27-141512_1080x1920_scrot](https://user-images.githubusercontent.com/51926728/80344424-c0881280-8891-11ea-9bd4-a1572a11038d.png)

**Comment by xjk971020** [comment]
localhost:8081,访问这个应该可以




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"465788227"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月27日(星期一) 下午3:17
收件人:&nbsp;"xjk971020/QQMusic"<QQMusic@noreply.github.com&gt;;
抄送:&nbsp;"佳"<823840954@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [xjk971020/QQMusic] 运行完后， localhost:8080 没有连接 (#2)





 
在终端：
 
 在VueUi:

**Comment by 465788227** [comment]
不是！既然如此，我还是用你的网站就好了！谢谢！

**Comment by xjk971020** [comment]
老哥你也是在学习前端吗
